### ISSUE TITLE
some bugs when using tensorflow 1.x

### ISSUE THREAD

**Issue by desperadoola** [tensorflow/text#173]
tensorflow_version=1.15

use BertTokenizer will cause 

```AttributeError: 'RaggedTensor' object has no attribute 'merge_dims'```

and use BasicTokenizer and set lower_case=True will cause 

```tensorflow.python.framework.errors_impl.InternalError: U_FILE_ACCESS_ERROR: Could not retrieve ICU NFKC_CaseFold normalizer [Op:CaseFoldUTF8]```

**Comment by broken** [comment]
I believe these are fixed in our most recent release. Can you install tensorflow_text==1.15.1 and let us know if you still experience any problems?

**Comment by desperadoola** [comment]
Thanks for your reply. I update the version of tensorflow_text to 1.15.1. It's perfect on eager mode,

```
tf.disable_v2_behavior()
tf.enable_eager_execution()

sent = tf.constant(u"The benefit of using these ops in your text preprocessing "
                                  "is that they are done in the TensorFlow graph.")

vocab_lookup_table = _create_table(
                    tf.constant(_load_vocab("./vocab.txt")))
tokenizer = tf_text.BertTokenizer(
          vocab_lookup_table, unknown_token="[UNK]", lower_case=True)

tokenized = tokenizer.tokenize(sent)
```

but when I denote the the first two lines, and run in graph mode, it gives me the following error

```
tensorflow.python.framework.errors_impl.InvalidArgumentError: Shape must be rank 1 but is rank 0 for 'RegexSplitWithOffsets' (op: 'RegexSplitWithOffsets') with input shapes: [], [], [].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aoluo/Documents/zhuiyi/pre-train/debug/wordpiece_vocabulary.py", line 570, in <module>
    tokenized = tokenizer.tokenize(sent)
  File "/Users/aoluo/anaconda3/lib/python3.6/site-packages/tensorflow_text/python/ops/bert_tokenizer.py", line 186, in tokenize
    tokens = self._basic_tokenizer.tokenize(text_input)
  File "/Users/aoluo/anaconda3/lib/python3.6/site-packages/tensorflow_text/python/ops/bert_tokenizer.py", line 91, in tokenize
    tokens, _, _ = self.tokenize_with_offsets(text_input)
  File "/Users/aoluo/anaconda3/lib/python3.6/site-packages/tensorflow_text/python/ops/bert_tokenizer.py", line 117, in tokenize_with_offsets
    "BertBasicTokenizer")
  File "/Users/aoluo/anaconda3/lib/python3.6/site-packages/tensorflow_text/python/ops/regex_split_ops.py", line 123, in regex_split_with_offsets
    keep_delim_regex_pattern))
  File "<string>", line 95, in regex_split_with_offsets
  File "/Users/aoluo/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/Users/aoluo/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/Users/aoluo/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/Users/aoluo/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/Users/aoluo/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1770, in __init__
    control_input_ops)
  File "/Users/aoluo/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1610, in _create_c_op
    raise ValueError(str(e))
ValueError: Shape must be rank 1 but is rank 0 for 'RegexSplitWithOffsets' (op: 'RegexSplitWithOffsets') with input shapes: [], [], [].
```

**Comment by desperadoola** [comment]
I changed ```tokenized = tokenizer.tokenize(sent)``` to ```tokenized = tokenizer.tokenize([sent])```, and it works. But I got a new error using tf_text.BertTokenizer

ERROR:tensorflow:Error recorded from training_loop: Op type not registered 'RegexSplitWithOffsets' in binary running on n-0f4208eb-w-0. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.
         [[node ParallelMapDataset_2 (defined at /lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]

**Comment by broken** [comment]
Did you change anything else? The previous error was supporting scalars for the regex split op (which we can do). However, this most recent one looks like it cannot find the op at all anymore. I believe this error would normally occur before the shape one, because the op needs to be registered for the input shapes to be validated. So I'm thinking something on your end has changed. Can you update tf text with pip and let me know if the error persists?

**Comment by desperadoola** [comment]
Nothing changed. The `"Op type not registered"` error happened when I run model with tf.string as input and BertTokenizer as tokenizer on TPU.

**Comment by HichemMaiza** [comment]
I am facing a similar issue With RegexSplitWithOffsets OP when using tensorflow serving 

Environment
-----------------
OS:
---- 
Ubuntu : Release 18.04
python : 3.6.9

Dependencies versions:
------------------------------
tensorflow  --  2.0.0
tensorflow-text  -- 2.0.1

Error :
--------
```
2019-12-16 14:59:30.379512: W external/org_tensorflow/tensorflow/core/framework/op_kernel.cc:1622] OP_REQUIRES failed at partitioned_function_ops.cc:113 : Not found: Op type not registered 'RegexSplitWithOffsets' in binary running on pc. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.
```
Error and Pipeline Description
----------------------------------------
I am using BertTokenizer in a tensorflow.keras.layers.Layer custom class

Training  `model.fit` --> works fine 
Evaluating `model.evaluate`--> works fine 
Saving `model.save` --> works fine
loading using `model.load` --> works fine 
serving with tensorflow serving --> ERROR 

When using tensorflow serving I get the `Not found: Op type not registered 'RegexSplitWithOffsets' ` error

**Comment by broken** [comment]
Oh. RegexSplitWithOffsets is not in TF Serving yet. I have a change I'm verifying/debugging today that adds this in.

**Comment by HichemMaiza** [comment]
@broken  Thanks a lot for your feedback.

**Comment by HichemMaiza** [comment]
@broken The same error is raising when using `tensorflowjs_converter` 

```
tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'RegexSplitWithOffsets' in binary running on pc. Make sure the Op and Kernel are registered in the binary running in this process.
```

**Comment by broken** [comment]
Looking at the FAQ for the converter (https://github.com/tensorflow/tfjs/tree/master/tfjs-converter), it only supports a subset of TF ops ([list here](https://github.com/tensorflow/tfjs/blob/master/tfjs-converter/docs/supported_ops.md)). None of our ops using custom kernels would be supported in tfjs then.

**Comment by HichemMaiza** [comment]
@broken  Thank your feedback, I appreciate your reactivity. 
Do you think that we will have a TF serving release soon with the support of `RegexSplitWithOffsets` ?

**Comment by broken** [comment]
Apologies for the delayed response, I sent code to update tf serving with the latest release, and built some infrastructure to make future updates easy. Because of the recent holidays, nobody on serving has been around to respond, and I too have been in & out. However, we should see this get updated soon now that the holidays are over and people are getting back from vacation.

**Comment by broken** [comment]
It took a long time to get the code approved, but tf text is now updated in tf serving (as of today), so this should no longer be an issue.
