### ISSUE TITLE
tokenizer doesn't work with tf.distribute.Strategy

### ISSUE THREAD

**Issue by terrykong** [tensorflow/text#199]
Hi guys,

My environment is tensorflow==2.0.0 and tensorflow_text==2.0.1

I'm wondering if there's a way to get tensorflow text to work with tensorflow's distributed strategies. Here's a minimal example that doesn't work for me. Note that if I remove tf.function, I can iterate through the dataset, but then i'm in eager mode and can't take advantage of executing things in a graph.

```python
import tensorflow as tf
import tensorflow_text as text

docs = tf.data.Dataset.from_tensor_slices([['Never tell me the odds.'],
                                           ["It's a trap!"]])
tokenizer = text.WhitespaceTokenizer()
tokenized_docs = docs.map(lambda x: tokenizer.tokenize(x))

def print_dataset(dataset):
    for x in dataset:
        tf.print(x)
print_dataset(tokenized_docs)
tf.function(print_dataset)(tokenized_docs)

strategy = tf.distribute.OneDeviceStrategy(device='/cpu:0')
distributed_dataset = strategy.experimental_distribute_dataset(tokenized_docs)
with strategy.scope():
    @tf.function
    def foo(dataset):
        for x in dataset:
            tf.print(x)

foo(distributed_dataset)

# OUTPUT
'''
2019-12-11 22:33:24.268738: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2019-12-11 22:33:24.297320: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2500000000 Hz
2019-12-11 22:33:24.305256: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x4d16340 executing computations on platform Host. Devices:
2019-12-11 22:33:24.305312: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/util/dispatch.py:180: batch_gather (from tensorflow.python.ops.array_ops) is deprecated and will be removed after 2017-10-25.
Instructions for updating:
`tf.batch_gather` is deprecated, please use `tf.gather` with `batch_dims=-1` instead.
<tf.RaggedTensor [[b'Never', b'tell', b'me', b'the', b'odds.']]>
<tf.RaggedTensor [[b"It's", b'a', b'trap!']]>
tf.RaggedTensor(values=Tensor("RaggedFromVariant/RaggedTensorFromVariant:1", shape=(None,), dtype=string), row_splits=Tensor("RaggedFromVariant/RaggedTensorFromVariant:0", shape=(None,), dtype=int64))
tf.RaggedTensor(values=Tensor("RaggedFromVariant/RaggedTensorFromVariant:1", shape=(None,), dtype=string), row_splits=Tensor("RaggedFromVariant/RaggedTensorFromVariant:0", shape=(None,), dtype=int64))
Traceback (most recent call last):
  File "test.py", line 48, in <module>
    foo(distributed_dataset)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/def_function.py", line 457, in __call__
    result = self._call(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/def_function.py", line 503, in _call
    self._initialize(args, kwds, add_initializers_to=initializer_map)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/def_function.py", line 408, in _initialize
    *args, **kwds))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/function.py", line 1848, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/function.py", line 2150, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/function.py", line 2041, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/func_graph.py", line 915, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/def_function.py", line 358, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/func_graph.py", line 905, in wrapper
    raise e.ag_error_metadata.to_exception(e)
TypeError: in converted code:

    test.py:45 foo  *
        for x in dataset:
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/autograph/operators/control_flow.py:337 for_stmt
        return custom_handler(extra_test, body, init_vars)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/distribute/input_lib.py:416 _autograph_for_loop
        self.reduce((constant_op.constant(0),), reduce_body_with_dummy_state)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/distribute/input_lib.py:422 reduce
        has_data, data = _get_next_as_optional(iterator, self._strategy)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/distribute/input_lib.py:200 _get_next_as_optional
        iterator._iterators[i].get_next_as_list(new_name))  # pylint: disable=protected-access
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/distribute/input_lib.py:878 get_next_as_list
        lambda: _dummy_tensor_fn(data.value_structure))
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/util/deprecation.py:507 new_func
        return func(*args, **kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/control_flow_ops.py:1174 cond
        return cond_v2.cond_v2(pred, true_fn, false_fn, name)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/cond_v2.py:91 cond_v2
        op_return_value=pred)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/func_graph.py:915 func_graph_from_py_func
        func_outputs = python_func(*func_args, **func_kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/distribute/input_lib.py:878 <lambda>
        lambda: _dummy_tensor_fn(data.value_structure))
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/distribute/input_lib.py:801 _dummy_tensor_fn
        result.append(create_dummy_tensor(feature_shape, feature_type))
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/distribute/input_lib.py:784 create_dummy_tensor
        for dim in feature_shape.dims:

    TypeError: 'NoneType' object is not iterable

'''
```

Removing the tokenizer seems to work
```python
import tensorflow as tf
import tensorflow_text as text

docs = tf.data.Dataset.from_tensor_slices([['Never tell me the odds.'],
                                           ["It's a trap!"]])

def print_dataset(dataset):
    for x in dataset:
        tf.print(x)
print_dataset(docs)
tf.function(print_dataset)(docs)

strategy = tf.distribute.OneDeviceStrategy(device='/cpu:0')
distributed_dataset = strategy.experimental_distribute_dataset(docs)
with strategy.scope():
    @tf.function
    def foo(dataset):
        for x in dataset:
            tf.print(x)

foo(distributed_dataset)

# OUTPUT
'''
2019-12-11 22:30:47.173794: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2019-12-11 22:30:47.202302: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2500000000 Hz
2019-12-11 22:30:47.210319: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x3369120 executing computations on platform Host. Devices:
2019-12-11 22:30:47.210378: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
["Never tell me the odds."]
["It\'s a trap!"]
["Never tell me the odds."]
["It\'s a trap!"]
["Never tell me the odds."]
["It\'s a trap!"]
'''
```

Any help or guidance would be appreciated

**Comment by thuang513** [comment]
Thanks for reporting this issue @terrykong! This looks like an issue with DistributionStrategy and RaggedTensor mentioned in [1]. Have you tried the workaround mentioned there?

[1] https://github.com/tensorflow/tensorflow/issues/32487

**Comment by thuang513** [comment]
(see https://github.com/tensorflow/tensorflow/issues/32487#issuecomment-536717493 for workaround)

**Comment by terrykong** [comment]
Hi @thuang513 
That looked promising, but unfortunately it didn't work for me. Just to be complete, I am using the docker image: `tensorflow/tensorflow:2.0.0-py3` and running `pip install tensorflow_text==2.0.1`

**Comment by terrykong** [comment]
Hi @thuang513,

Is it possible to reopen this because the above fix didn't work for this simple example and I haven't found a workaround for this issue.

**Comment by broken** [comment]
small update.. we're reaching out to one of the distribution strategy authors to help address this.

**Comment by terrykong** [comment]
So I just recently tried `tensorflow/tensorflow:2.1.0-py3` with `pip install tensorflow_text==2.1.0rc0` and the above example now works. I'll close this since I now have a way forward. Thanks!
