### ISSUE TITLE
Use pre-trained sentencepiece model with SentencepieceTokenizer

### ISSUE THREAD

**Issue by ramji-c** [tensorflow/text#278]
I am trying to load a pre-trained sentencepiece model using the SentencepieceTokenizer, but got internal error as mentioned in issue #215 . I then made the suggested changes to read model file, but now get a unicode error show below. Any suggestions?

Tensorflow version: 2.1.0
Tensorflow text version: 2.1.1
OS: MacOs 10.15.3

`Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/rchandrasekara/anaconda3/envs/lx-sort/lib/python3.7/site-packages/tensorflow_core/python/lib/io/file_io.py", line 128, in read
    pywrap_tensorflow.ReadFromStream(self._read_buf, length))
  File "/Users/rchandrasekara/anaconda3/envs/lx-sort/lib/python3.7/site-packages/tensorflow_core/python/lib/io/file_io.py", line 98, in _prepare_value
    return compat.as_str_any(val)
  File "/Users/rchandrasekara/anaconda3/envs/lx-sort/lib/python3.7/site-packages/tensorflow_core/python/util/compat.py", line 139, in as_str_any
    return as_str(value)
  File "/Users/rchandrasekara/anaconda3/envs/lx-sort/lib/python3.7/site-packages/tensorflow_core/python/util/compat.py", line 109, in as_text
    return bytes_or_text.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xae in position 53: invalid start byte`

**Comment by ramji-c** [comment]
changing read more to "rb" did the trick.
