### ISSUE TITLE
NotFoundError on load_library.load_op_library(resource_loader.get_path_to_datafile('_text_similarity_metric_ops.so'))

### ISSUE THREAD

**Issue by sbatururimi** [tensorflow/text#453]
Built tensorflow 2.3.0 from sources with success (gpu detected and working). Then built tensorflow-text from source also (matching the version to be 2.3.0) but when truing to import the tensorflow_text module, I got an error syaing that _text_similarity_metric_ops.so is missing (and it is).

```
>>> import tensorflow_text as text
2020-11-29 03:08:10.583787: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.11.0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/virt1/Development/tensorflow-text/tensorflow_text/__init__.py", line 21, in <module>
    from tensorflow_text.python import metrics
  File "/home/virt1/Development/tensorflow-text/tensorflow_text/python/metrics/__init__.py", line 20, in <module>
    from tensorflow_text.python.metrics.text_similarity_metric_ops import *
  File "/home/virt1/Development/tensorflow-text/tensorflow_text/python/metrics/text_similarity_metric_ops.py", line 28, in <module>
    gen_text_similarity_metric_ops = load_library.load_op_library(resource_loader.get_path_to_datafile('_text_similarity_metric_ops.so'))
  File "/home/virt1/venvs/py38_tf2_3_0_pegasus/lib/python3.8/site-packages/tensorflow/python/framework/load_library.py", line 58, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/virt1/Development/tensorflow-text/tensorflow_text/python/metrics/_text_similarity_metric_ops.so: cannot open shared object file: No such file or directory
```
How could I fix that? Tried from tagged commit, from master, from pypi - same error everywhere.

**Comment by sbatururimi** [comment]
Found my error, was trying to load the library within the directory tensorflow-text 👎 , going to another folder solved the issue.
