### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: /usr/local/lib/python3.6/dist-packages/tensorflow_text/python/metrics/_text_similarity_metric_ops.so: undefined symbol: _ZNK10tensorflow8OpKernel11TraceStringERKNS_15OpKernelContextEb

### ISSUE THREAD

**Issue by yananchen1989** [tensorflow/text#543]
tensorflow version: 2.3.1

➜  `python -c "import tensorflow_text"`

> 2021-03-24 03:43:49.956508: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_text/__init__.py", line 21, in <module>
>     from tensorflow_text.python import metrics
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_text/python/metrics/__init__.py", line 20, in <module>
>     from tensorflow_text.python.metrics.text_similarity_metric_ops import *
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_text/python/metrics/text_similarity_metric_ops.py", line 28, in <module>
>     gen_text_similarity_metric_ops = load_library.load_op_library(resource_loader.get_path_to_datafile('_text_similarity_metric_ops.so'))
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/load_library.py", line 58, in load_op_library
>     lib_handle = py_tf.TF_LoadLibrary(library_filename)
> tensorflow.python.framework.errors_impl.NotFoundError: /usr/local/lib/python3.6/dist-packages/tensorflow_text/python/metrics/_text_similarity_metric_ops.so: undefined symbol: _ZNK10tensorflow8OpKernel11TraceStringERKNS_15OpKernelContextEb

**Comment by yananchen1989** [comment]
when I tried to install tensorflow_text, it converts my tf version to 2.4.1, which is not the version compatible with my GPU driver.
